WildlifeTracker/config/routes.rb
Rails.application.routes.draw do
  resources :sightings
  resources :species

end

WildlifeTracker/app/models/sighting.rb
class Sighting < ActiveRecord::Base
  validate do
       errors[:date] << "cannot be in the future" if date && date > Date.today
     end
  validates :latitude, :numericality => true
  validates :longitude, :numericality => true

  belongs_to :species
end

WildlifeTracker/app/models/species.rb
class Species < ActiveRecord::Base
  validates :animal => :presence => true

  has_many :sighting
end

WildlifeTracker/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

WildlifeTracker/app/controllers/sightings_controller.rb
class SightingsController < ApplicationController
  before_action :set_sighting, only: [:show, :edit, :update, :destroy]

  # GET /sightings
  # GET /sightings.json
  def index
    @sightings = Sighting.all
  end

  # GET /sightings/1
  # GET /sightings/1.json
  def show
  end

  # GET /sightings/new
  def new
    @sighting = Sighting.new
  end

  # GET /sightings/1/edit
  def edit
  end

  # POST /sightings
  # POST /sightings.json
  def create
    @sighting = Sighting.new(sighting_params)

    respond_to do |format|
      if @sighting.save
        format.html { redirect_to @sighting, notice: 'Sighting was successfully created.' }
        format.json { render :show, status: :created, location: @sighting }
      else
        format.html { render :new }
        format.json { render json: @sighting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sightings/1
  # PATCH/PUT /sightings/1.json
  def update
    respond_to do |format|
      if @sighting.update(sighting_params)
        format.html { redirect_to @sighting, notice: 'Sighting was successfully updated.' }
        format.json { render :show, status: :ok, location: @sighting }
      else
        format.html { render :edit }
        format.json { render json: @sighting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sightings/1
  # DELETE /sightings/1.json
  def destroy
    @sighting.destroy
    respond_to do |format|
      format.html { redirect_to sightings_url, notice: 'Sighting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sighting
      @sighting = Sighting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sighting_params
      params.require(:sighting).permit(:date, :latitude, :longitude)
    end
end

WildlifeTracker/app/controllers/species_controller.rb
class SpeciesController < ApplicationController
  before_action :set_species, only: [:show, :edit, :update, :destroy]

  # GET /species
  # GET /species.json
  def index
    @species = Species.all
  end

  # GET /species/1
  # GET /species/1.json
  def show
  end

  # GET /species/new
  def new
    @species = Species.new
  end

  # GET /species/1/edit
  def edit
  end

  # POST /species
  # POST /species.json
  def create
    @species = Species.new(species_params)

    respond_to do |format|
      if @species.save
        format.html { redirect_to @species, notice: 'Species was successfully created.' }
        format.json { render :show, status: :created, location: @species }
      else
        format.html { render :new }
        format.json { render json: @species.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /species/1
  # PATCH/PUT /species/1.json
  def update
    respond_to do |format|
      if @species.update(species_params)
        format.html { redirect_to @species, notice: 'Species was successfully updated.' }
        format.json { render :show, status: :ok, location: @species }
      else
        format.html { render :edit }
        format.json { render json: @species.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /species/1
  # DELETE /species/1.json
  def destroy
    @species.destroy
    respond_to do |format|
      format.html { redirect_to species_index_url, notice: 'Species was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_species
      @species = Species.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def species_params
      params.require(:species).permit(:animal)
    end
end

WildlifeTracker/app/helpers/application_helper.rb
module ApplicationHelper
end

WildlifeTracker/app/helpers/sightings_helper.rb
module SightingsHelper
end

WildlifeTracker/app/helpers/species_helper.rb
module SpeciesHelper
end

WildlifeTracker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WildlifeTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

WildlifeTracker/app/views/sightings/_form.html.erb
<%= form_for(@sighting) do |f| %>
  <% if @sighting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sighting.errors.count, "error") %> prohibited this sighting from being saved:</h2>

      <ul>
      <% @sighting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

WildlifeTracker/app/views/sightings/edit.html.erb
<h1>Editing Sighting</h1>

<%= render 'form' %>

<%= link_to 'Show', @sighting %> |
<%= link_to 'Back', sightings_path %>

WildlifeTracker/app/views/sightings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sightings</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sightings.each do |sighting| %>
      <tr>
        <td><%= sighting.date %></td>
        <td><%= sighting.latitude %></td>
        <td><%= sighting.longitude %></td>
        <td><%= link_to 'Show', sighting %></td>
        <td><%= link_to 'Edit', edit_sighting_path(sighting) %></td>
        <td><%= link_to 'Destroy', sighting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sighting', new_sighting_path %>

WildlifeTracker/app/views/sightings/new.html.erb
<h1>New Sighting</h1>

<%= render 'form' %>

<%= link_to 'Back', sightings_path %>

WildlifeTracker/app/views/sightings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @sighting.date %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @sighting.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @sighting.longitude %>
</p>

<%= link_to 'Edit', edit_sighting_path(@sighting) %> |
<%= link_to 'Back', sightings_path %>

WildlifeTracker/app/views/species/_form.html.erb
<%= form_for(@species) do |f| %>
  <% if @species.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@species.errors.count, "error") %> prohibited this species from being saved:</h2>

      <ul>
      <% @species.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :animal %><br>
    <%= f.text_field :animal %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

WildlifeTracker/app/views/species/edit.html.erb
<h1>Editing Species</h1>

<%= render 'form' %>

<%= link_to 'Show', @species %> |
<%= link_to 'Back', species_index_path %>

WildlifeTracker/app/views/species/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Species</h1>

<table>
  <thead>
    <tr>
      <th>Animal</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @species.each do |species| %>
      <tr>
        <td><%= species.animal %></td>
        <td><%= link_to 'Show', species %></td>
        <td><%= link_to 'Edit', edit_species_path(species) %></td>
        <td><%= link_to 'Destroy', species, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Species', new_species_path %>

WildlifeTracker/app/views/species/new.html.erb
<h1>New Species</h1>

<%= render 'form' %>

<%= link_to 'Back', species_index_path %>

WildlifeTracker/app/views/species/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Animal:</strong>
  <%= @species.animal %>
</p>

<%= link_to 'Edit', edit_species_path(@species) %> |
<%= link_to 'Back', species_index_path %>